name: Create DataBricks Workspace

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the 'main' branch

jobs:
  create_workspace:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: pietrobolcato/install-azure-cli-action@v1.0.1
        
      - name: Install Azure CLI Databricks extension
        run: az extension add --name databricks
        
      - name: Azure CLI Login
        id: azure_login
        run: |
          az login --service-principal --tenant ${{ secrets.AZURE_TENANT_ID }} --username ${{ secrets.AZURE_CLIENT_ID }} --password ${{ secrets.AZURE_CLIENT_SECRET }}
      
      - name: Check if Azure Databricks workspace exists
        id: check_workspace
        run: |
          workspace=$(az databricks workspace show --resource-group rg-test-clarins --name databricks_workspace --query 'workspaceUrl' -o tsv)
          if [ -n "$workspace" ]; then
            echo "Workspace already exists"
            echo "::set-output name=workspace-exists::true"
          else
            echo "Workspace does not exist"
            echo "::set-output name=workspace-exists::false"
          fi
          
      - name: Create Azure Databricks workspace
        if: steps.check_workspace.outputs.workspace-exists == 'false'
        run: |
          az databricks workspace create --resource-group rg-test-clarins --name databricks_workspace --location centralindia
