name: Create DataBricks Workspace

on:
  workflow_dispatch:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the 'main' branch

jobs:
  create_workspace:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Azure CLI
        uses: pietrobolcato/install-azure-cli-action@v1.0.1
        
        
      - name: Azure CLI Login
        id: azure_login
        run: |
          az login --service-principal --tenant ${{ secrets.AZURE_TENANT_ID }} --username ${{ secrets.AZURE_CLIENT_ID }} --password ${{ secrets.AZURE_CLIENT_SECRET }}

     
      - name: Install Azure CLI Databricks extension
        run: az extension add --name databricks
        
      
      - name: Check if Azure Databricks workspace exists and create
        run: |
          if az databricks workspace show --resource-group MLOPS --name prod_workspace --query 'workspaceUrl' -o tsv; then
            echo "Workspace already exists"
          else
            echo "Creating the workspace"
            az databricks workspace create --resource-group MLOPS --name prod_workspace --location centralindia
          fi
