name: Run the notebooks on data bricks workspace

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-databricks-notebook:
   runs-on: ubuntu-latest

   steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Trigger notebook in workspace
        uses: databricks/run-notebook@v0
        with:
          local-notebook-path: src/Data_preparation/snowflake_connectivity.py
          databricks-host: https://adb-8209232505015077.17.azuredatabricks.net
          databricks-token: ${{ secrets.DATABRICKS_TOKEN }}
          git-commit: ${{ github.event.push.head.sha }}
          #existing-cluster-id: 0704-124839-3hgqqh0e
          new-cluster-json: >
           {
             "num_workers": 1,
             "spark_version": "10.4.x-scala2.12",
             "node_type_id": "Standard_D3_v2"
           }
