name: Run notebooks on data bricks workspace

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-databricks-notebook:
   runs-on: ubuntu-latest

   steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Trigger 1st notebook in workspace
        uses: databricks/run-notebook@v0
        with:
          local-notebook-path: src/Libraries.py
          databricks-host: https://adb-7641799796704776.16.azuredatabricks.net
          databricks-token: ${{ secrets.DATABRICKS_TOKEN }}
          git-commit: ${{ github.event.push.head.sha }}
          #existing-cluster-id: 0704-124839-3hgqqh0e
          new-cluster-json: >
           {
             "num_workers": 1,
             "spark_version": "11.3.x-scala2.12",
             "node_type_id": "Standard_DS3_v2"
           }
           
      - name: Trigger 2nd notebook in workspace
        uses: databricks/run-notebook@v0
        with:
          local-notebook-path: src/Data_preparation/snowflake_connectivity.py
          databricks-host: https://adb-7641799796704776.16.azuredatabricks.net
          databricks-token: ${{ secrets.DATABRICKS_TOKEN }}
          git-commit: ${{ github.event.push.head.sha }}
          #existing-cluster-id: 0704-124839-3hgqqh0e
          new-cluster-json: >
           {
             "num_workers": 1,
             "spark_version": "11.3.x-scala2.12",
             "node_type_id": "Standard_DS3_v2"
           }
      - name: Trigger 3rd notebook in workspace
        uses: databricks/run-notebook@v0
        with:
          local-notebook-path: src/Data_preparation/EDA.py
          databricks-host: https://adb-7641799796704776.16.azuredatabricks.net
          databricks-token: ${{ secrets.DATABRICKS_TOKEN }}
          git-commit: ${{ github.event.push.head.sha }}
          #existing-cluster-id: 0704-124839-3hgqqh0e
          new-cluster-json: >
           {
             "num_workers": 1,
             "spark_version": "11.3.x-scala2.12",
             "node_type_id": "Standard_DS3_v2"
           }
           
      - name: Trigger 4th notebook in workspace
        uses: databricks/run-notebook@v0
        with:
          local-notebook-path: src/Model_Preparation/Model_Training.py
          databricks-host: https://adb-7641799796704776.16.azuredatabricks.net
          databricks-token: ${{ secrets.DATABRICKS_TOKEN }}
          git-commit: ${{ github.event.push.head.sha }}
          #existing-cluster-id: 0704-124839-3hgqqh0e
          new-cluster-json: >
           {
             "num_workers": 1,
             "spark_version": "11.3.x-scala2.12",
             "node_type_id": "Standard_DS3_v2"
           }
           
      - name: Trigger 5th notebook in workspace
        uses: databricks/run-notebook@v0
        with:
          local-notebook-path: src/Model_Preparation/Model_Registering.py
          databricks-host: https://adb-7641799796704776.16.azuredatabricks.net
          databricks-token: ${{ secrets.DATABRICKS_TOKEN }}
          git-commit: ${{ github.event.push.head.sha }}
          #existing-cluster-id: 0704-124839-3hgqqh0e
          new-cluster-json: >
           {
             "num_workers": 1,
             "spark_version": "11.3.x-scala2.12",
             "node_type_id": "Standard_DS3_v2"
           }
           
      - name: Trigger 6th notebook in workspace
        uses: databricks/run-notebook@v0
        with:
          local-notebook-path: src/Model_Preparation/Batch_Inferencing.py
          databricks-host: https://adb-7641799796704776.16.azuredatabricks.net
          databricks-token: ${{ secrets.DATABRICKS_TOKEN }}
          git-commit: ${{ github.event.push.head.sha }}
          #existing-cluster-id: 0704-124839-3hgqqh0e
          new-cluster-json: >
           {
             "num_workers": 1,
             "spark_version": "11.3.x-scala2.12",
             "node_type_id": "Standard_DS3_v2"
           }
      - name: Trigger 7th notebook in workspace
        uses: databricks/run-notebook@v0
        with:
          local-notebook-path: src/Model_Preparation/Model_Serving.py
          databricks-host: https://adb-7641799796704776.16.azuredatabricks.net
          databricks-token: ${{ secrets.DATABRICKS_TOKEN }}
          git-commit: ${{ github.event.push.head.sha }}
          #existing-cluster-id: 0704-124839-3hgqqh0e
          new-cluster-json: >
           {
             "num_workers": 1,
             "spark_version": "11.3.x-scala2.12",
             "node_type_id": "Standard_DS3_v2"
           }

