name: Run the notebooks on data bricks workspace

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        
      - name: Trigger notebook in workspace
        uses: databricks/run-notebook@v0
        with:
          local-notebook-path: src/Data_preparation/snowflake_connectivity.py
          databricks-host: https://adb-7150091277937564.4.azuredatabricks.net
          databricks-token: ${{ secrets.DATABRICKS_TOKEN }}
          existing-cluster-id: '0703-075025-4qvvdoqv'
