name: Training

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the 'main' branch

jobs:
  Training:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
          python-version: 3.9
    - name: Build
      run: |
          pip install databricks-cli
          echo "
           [DEFAULT]
           host = https://adb-3916899102849780.0.azuredatabricks.net
           token = dapidf17aacba236669e3c3bb739bf3f917f

           " > ~/.databrickscfg
          echo "$(cat ~/.databrickscfg)"
          databricks repos update --repo-id 3832722857797688 --branch main
          
