name: Run notebooks on data bricks workspace

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-databricks-notebook:
   runs-on: ubuntu-latest

   steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Trigger 1st notebook in workspace
        uses: databricks/run-notebook@v0
        with:
          local-notebook-path: src/Libraries.py
          databricks-host: https://adb-8209232505015077.17.azuredatabricks.net
          databricks-token: ${{ secrets.DATABRICKS_TOKEN }}
          git-commit: ${{ github.event.push.head.sha }}
          existing-cluster-id: 0706-111411-bmi9yydy
          
      - name: Trigger 2nd notebook in workspace
        uses: databricks/run-notebook@v0
        with:
          local-notebook-path: src/Data_preparation/snowflake_connectivity.py
          databricks-host: https://adb-8209232505015077.17.azuredatabricks.net
          databricks-token: ${{ secrets.DATABRICKS_TOKEN }}
          git-commit: ${{ github.event.push.head.sha }}
          existing-cluster-id: 0706-111411-bmi9yydy
          
      - name: Trigger 3rd notebook in workspace
        uses: databricks/run-notebook@v0
        with:
          local-notebook-path: src/Data_preparation/EDA.py
          databricks-host: https://adb-8209232505015077.17.azuredatabricks.net
          databricks-token: ${{ secrets.DATABRICKS_TOKEN }}
          git-commit: ${{ github.event.push.head.sha }}
          existing-cluster-id: 0706-111411-bmi9yydy
           
      - name: Trigger 4th notebook in workspace
        uses: databricks/run-notebook@v0
        with:
          local-notebook-path: src/Model_Preparation/Model_Training.py
          databricks-host: https://adb-8209232505015077.17.azuredatabricks.net
          databricks-token: ${{ secrets.DATABRICKS_TOKEN }}
          git-commit: ${{ github.event.push.head.sha }}
          existing-cluster-id: 0706-111411-bmi9yydy
      
           
      - name: Trigger 5th notebook in workspace
        uses: databricks/run-notebook@v0
        with:
          local-notebook-path: src/Model_Preparation/Model_Registering.py
          databricks-host: https://adb-8209232505015077.17.azuredatabricks.net
          databricks-token: ${{ secrets.DATABRICKS_TOKEN }}
          git-commit: ${{ github.event.push.head.sha }}
          existing-cluster-id: 0706-111411-bmi9yydy
         
      - name: Trigger 6th notebook in workspace
        uses: databricks/run-notebook@v0
        with:
          local-notebook-path: src/Model_Preparation/Batch_Inferencing.py
          databricks-host: https://adb-8209232505015077.17.azuredatabricks.net
          databricks-token: ${{ secrets.DATABRICKS_TOKEN }}
          git-commit: ${{ github.event.push.head.sha }}
          existing-cluster-id: 0706-111411-bmi9yydy
         
      - name: Trigger 7th notebook in workspace
        uses: databricks/run-notebook@v0
        with:
          local-notebook-path: src/Model_Preparation/Model_Serving.py
          databricks-host: https://adb-8209232505015077.17.azuredatabricks.net
          databricks-token: ${{ secrets.DATABRICKS_TOKEN }}
          git-commit: ${{ github.event.push.head.sha }}
          existing-cluster-id: 0706-111411-bmi9yydy
